server:
  port: 9090
  servlet:
    context-path: /geo-service

app:
  version: "@project.version@"
  name: "@project.name@"

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/geo
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

wikimapia:
  url:
    http://api.wikimapia.org
  key:
    example

joinfaces:
  faces:
    project-stage: development
